// Mock data for chat components
import type { Chat, Message } from './types';

export const mockChats: Chat[] = [
  {
    id: '1',
    name: 'Sarah Chen',
    type: 'direct',
    lastMessage: 'Hey! Are you coming to the meeting?',
    lastMessageTime: new Date(Date.now() - 5 * 60 * 1000),
    unreadCount: 3,
    isOnline: true,
  },
  {
    id: '2',
    name: 'Team Wave',
    type: 'group',
    lastMessage: 'Alex: The new design looks great!',
    lastMessageTime: new Date(Date.now() - 15 * 60 * 1000),
    unreadCount: 0,
    isOnline: false,
  },
  {
    id: '3',
    name: 'Jordan Kim',
    type: 'direct',
    lastMessage: 'Thanks for the help yesterday!',
    lastMessageTime: new Date(Date.now() - 60 * 60 * 1000),
    unreadCount: 1,
    isOnline: false,
  },
  {
    id: '4',
    name: 'Product Updates',
    type: 'channel',
    lastMessage: 'Version 2.0 is now live!',
    lastMessageTime: new Date(Date.now() - 2 * 60 * 60 * 1000),
    unreadCount: 5,
    isOnline: false,
  },
  {
    id: '5',
    name: 'Alex Rivera',
    type: 'direct',
    lastMessage: 'See you tomorrow!',
    lastMessageTime: new Date(Date.now() - 3 * 60 * 60 * 1000),
    unreadCount: 0,
    isOnline: true,
  },
  {
    id: '6',
    name: 'Design Team',
    type: 'group',
    lastMessage: 'Morgan: I\'ll share the mockups soon',
    lastMessageTime: new Date(Date.now() - 24 * 60 * 60 * 1000),
    unreadCount: 0,
    isOnline: false,
  },
  {
    id: '7',
    name: 'Casey Brown',
    type: 'direct',
    lastMessage: 'Got it, thanks!',
    lastMessageTime: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    unreadCount: 0,
    isOnline: false,
  },
  {
    id: '8',
    name: 'Engineering',
    type: 'channel',
    lastMessage: 'New deployment pipeline ready',
    lastMessageTime: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    unreadCount: 12,
    isOnline: false,
  },
];

export const mockMessages: Record<string, Message[]> = {
  '1': [
    {
      id: 'm1',
      chatId: '1',
      senderId: 'sarah',
      senderName: 'Sarah Chen',
      content: 'Hey there! How are you doing?',
      timestamp: new Date(Date.now() - 30 * 60 * 1000),
      isOwn: false,
      isRead: true,
    },
    {
      id: 'm2',
      chatId: '1',
      senderId: 'me',
      senderName: 'Me',
      content: 'Hi Sarah! I\'m doing great, thanks for asking. How about you?',
      timestamp: new Date(Date.now() - 28 * 60 * 1000),
      isOwn: true,
      isRead: true,
    },
    {
      id: 'm3',
      chatId: '1',
      senderId: 'sarah',
      senderName: 'Sarah Chen',
      content: 'Pretty good! Just finished the project review.',
      timestamp: new Date(Date.now() - 25 * 60 * 1000),
      isOwn: false,
      isRead: true,
    },
    {
      id: 'm4',
      chatId: '1',
      senderId: 'me',
      senderName: 'Me',
      content: 'Nice! How did it go?',
      timestamp: new Date(Date.now() - 20 * 60 * 1000),
      isOwn: true,
      isRead: true,
    },
    {
      id: 'm5',
      chatId: '1',
      senderId: 'sarah',
      senderName: 'Sarah Chen',
      content: 'Really well! The team loved the new features we added.',
      timestamp: new Date(Date.now() - 15 * 60 * 1000),
      isOwn: false,
      isRead: true,
    },
    {
      id: 'm6',
      chatId: '1',
      senderId: 'sarah',
      senderName: 'Sarah Chen',
      content: 'Hey! Are you coming to the meeting?',
      timestamp: new Date(Date.now() - 5 * 60 * 1000),
      isOwn: false,
      isRead: false,
    },
  ],
  '2': [
    {
      id: 'm7',
      chatId: '2',
      senderId: 'alex',
      senderName: 'Alex Rivera',
      content: 'Just pushed the latest changes to staging',
      timestamp: new Date(Date.now() - 60 * 60 * 1000),
      isOwn: false,
      isRead: true,
    },
    {
      id: 'm8',
      chatId: '2',
      senderId: 'me',
      senderName: 'Me',
      content: 'Great work! I\'ll review them this afternoon.',
      timestamp: new Date(Date.now() - 45 * 60 * 1000),
      isOwn: true,
      isRead: true,
    },
    {
      id: 'm9',
      chatId: '2',
      senderId: 'jordan',
      senderName: 'Jordan Kim',
      content: 'The new design looks great!',
      timestamp: new Date(Date.now() - 15 * 60 * 1000),
      isOwn: false,
      isRead: true,
    },
  ],
  '3': [
    {
      id: 'm10',
      chatId: '3',
      senderId: 'me',
      senderName: 'Me',
      content: 'No problem! Happy to help anytime.',
      timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
      isOwn: true,
      isRead: true,
    },
    {
      id: 'm11',
      chatId: '3',
      senderId: 'jordan',
      senderName: 'Jordan Kim',
      content: 'Thanks for the help yesterday!',
      timestamp: new Date(Date.now() - 60 * 60 * 1000),
      isOwn: false,
      isRead: false,
    },
  ],
};

mockChats.push(
    {
      id: '9',
      name: 'Marketing Squad',
      type: 'group',
      lastMessage: 'Dana: Final draft is ready for review!',
      lastMessageTime: new Date(Date.now() - 4 * 60 * 60 * 1000),
      unreadCount: 2,
      isOnline: false,
    },
    {
      id: '10',
      name: 'Chris Dalton',
      type: 'direct',
      lastMessage: 'Let’s catch up this weekend!',
      lastMessageTime: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
      unreadCount: 0,
      isOnline: true,
    },
    {
      id: '11',
      name: 'HR Announcements',
      type: 'channel',
      lastMessage: 'Reminder: Submit your timesheets.',
      lastMessageTime: new Date(Date.now() - 8 * 60 * 60 * 1000),
      unreadCount: 7,
      isOnline: false,
    },
    {
      id: '12',
      name: 'DevOps Team',
      type: 'group',
      lastMessage: 'Sam: Deployment completed successfully.',
      lastMessageTime: new Date(Date.now() - 6 * 60 * 60 * 1000),
      unreadCount: 0,
      isOnline: false,
    },
    {
      id: '13',
      name: 'Mia Roberts',
      type: 'direct',
      lastMessage: 'Can you send the file?',
      lastMessageTime: new Date(Date.now() - 3 * 60 * 60 * 1000),
      unreadCount: 1,
      isOnline: false,
    }
);


// Generate empty messages for other chats
['4', '5', '6', '7', '8'].forEach((chatId) => {
  if (!mockMessages[chatId]) {
    mockMessages[chatId] = [
      {
        id: `msg-${chatId}-1`,
        chatId,
        senderId: 'other',
        senderName: mockChats.find((c) => c.id === chatId)?.name || 'User',
        content: mockChats.find((c) => c.id === chatId)?.lastMessage || 'Hello!',
        timestamp: mockChats.find((c) => c.id === chatId)?.lastMessageTime || new Date(),
        isOwn: false,
        isRead: true,
      },
    ];
  }
});

